# ------------------------------------------------------------------------
# Copyright (C) 2016 Andrzej Pronobis - All Rights Reserved
#
# This file is part of LibSPN. Unauthorized use or copying of this file,
# via any medium is strictly prohibited. Proprietary and confidential.
# ------------------------------------------------------------------------

from itertools import chain, combinations, product
import tensorflow as tf
from libspn.graph.scope import Scope
from libspn.graph.node import OpNode, Input
from libspn.inference.type import InferenceType
from libspn import utils
from libspn.exceptions import StructureError
from libspn.log import get_logger

import numpy as np


class PermProducts(OpNode):
    """A node representing multiple products, permuted over the input space, in an SPN.

    Args:
        *values (input_like): Inputs providing input values to this node.
            See :meth:`~libspn.Input.as_input` for possible values. The only
            criterion for the input is that all inputs, in the list, should
            have the same dimention.
        name (str): Name of the node.
    """

    logger = get_logger()
    info = logger.info

    def __init__(self, *values, name="PermProducts"):
        self._values = []
        super().__init__(InferenceType.MARGINAL, name)
        self.set_values(*values)

        # Check if all inputs share a common size.
        value_sizes = self.get_input_sizes()
        if not len(set(value_sizes)) == 1:
            raise StructureError("Each input to %s should be of the same size,"
                                 " but are of size %s " % (self, value_sizes))

        input_size = value_sizes[0]
        num_inputs = len(values)

        # Calculate numbed of products this node would model.
        if num_inputs == 1 or input_size == 1:
            self._num_prods = 1
        else:
            self._num_prods = pow(input_size, num_inputs)

        # Create indices by permuting over the input space, such that inputs
        # for the products can be generated by gathering from concatenated
        # values of the node.
        self._permuted_indices = self.permute_indices(num_inputs, input_size)

    def serialize(self):
        data = super().serialize()
        data['values'] = [(i.node.name, i.indices) for i in self._values]
        return data

    def deserialize(self, data):
        super().deserialize(data)
        self.set_values()

    def deserialize_inputs(self, data, nodes_by_name):
        super().deserialize_inputs(data, nodes_by_name)
        self._values = tuple(Input(nodes_by_name[nn], i)
                             for nn, i in data['values'])

    @property
    @utils.docinherit(OpNode)
    def inputs(self):
        return self._values

    @property
    def values(self):
        """list of Input: List of value inputs."""
        return self._values

    def set_values(self, *values):
        """Set the inputs providing input values to this node. If no arguments
        are given, all existing value inputs get disconnected.

        Args:
            *values (input_like): Inputs providing input values to this node.
                See :meth:`~libspn.Input.as_input` for possible values.
        """
        self._values = self._parse_inputs(*values)

    def permute_indices(self, num_inputs, input_size):
        """Create indices by permuting over the input space, such that inputs
        for the products can be generated by gathering from concatenated values
        of the node.

        Args:
            num_inputs (int): No. of inputs to this node.
            input_size (int): Size of each input.
        """
        ind = np.arange(input_size)
        ind_list = list(product(ind, repeat=num_inputs))
        indices_for_gather = np.array(ind_list, dtype=np.int)
        offset = np.linspace(0, (num_inputs*input_size)-input_size,
                             num=num_inputs, dtype=np.int)
        return (indices_for_gather + offset).flatten()

    # TODO: Is this method needed for PermProducts?
    #       If so, then permuted_indices should be  recalculated.
    def add_values(self, *values):
        """Add more inputs providing input values to this node.

        Args:
            *values (input_like): Inputs providing input values to this node.
                See :meth:`~libspn.Input.as_input` for possible values.
        """
        self._values = self._values + self._parse_inputs(*values)

    @property
    def _const_out_size(self):
        return True

    def _compute_out_size(self, *input_out_sizes):
        return self._num_prods

    def _compute_scope(self, *value_scopes):
        if not self._values:
            raise StructureError("%s is missing input values." % self)
        value_scopes = self._gather_input_scopes(*value_scopes)
        return [Scope.merge_scopes(chain.from_iterable(value_scopes))]

    def _compute_valid(self, *value_scopes):
        if not self._values:
            raise StructureError("%s is missing input values." % self)
        value_scopes_ = self._gather_input_scopes(*value_scopes)
        # If already invalid, return None
        if any(s is None for s in value_scopes_):
            return None
        # Check product decomposability
        flat_value_scopes = list(chain.from_iterable(value_scopes_))
        for s1, s2 in combinations(flat_value_scopes, 2):
            if s1 & s2:
                Product.info("%s is not decomposable with input value scopes %s",
                             self, flat_value_scopes)
                return None
        return self._compute_scope(*value_scopes)

    def _compute_value_common(self, *value_tensors):
        """Common actions when computing value."""
        # Check inputs
        if not self._values:
            raise StructureError("%s is missing input values." % self)
        # Prepare values
        value_tensors = self._gather_input_tensors(*value_tensors)
        if len(value_tensors) > 1:
            values = tf.concat_v2(value_tensors, 1)
        else:
            values = value_tensors[0]
        if self._num_prods > 1:
            # Gather values based on permuted_indices
            permuted_values = utils.gather_cols(values, self._permuted_indices)

            # Shape of values tensor = [Batch, (num_prods * num_vals)]
            # First, split the values tensor into 'num_prods' smaller tensors.
            # Then pack the split tensors together such that the new shape
            # of values tensor = [num_prods, Batch, num_vals]
            reshaped_values = tf.stack(tf.split(permuted_values, self._num_prods, 1))
            return reshaped_values
        else:
            return values

    def _compute_value(self, *value_tensors):
        values = self._compute_value_common(*value_tensors)
        if self._num_prods > 1:
            return tf.transpose(tf.reduce_prod(values, axis=-1))
        else:
            return tf.reduce_prod(values, axis=-1, keep_dims=True)

    def _compute_log_value(self, *value_tensors):
        values = self._compute_value_common(*value_tensors)
        if self._num_prods > 1:
            return tf.transpose(tf.reduce_sum(values, axis=-1))
        else:
            return tf.reduce_sum(values, axis=-1, keep_dims=True)

    def _compute_mpe_value(self, *value_tensors):
        return self._compute_value(*value_tensors)

    def _compute_log_mpe_value(self, *value_tensors):
        return self._compute_log_value(*value_tensors)

    def _compute_mpe_path(self, counts, *value_values, add_random=False, use_unweighted=False):
        # Check inputs
        if not self._values:
            raise StructureError("%s is missing input values." % self)

        def process_input(v_input, v_value):
            input_size = v_input.get_size(v_value)
            # Tile the counts if input is larger than 1
            return (tf.tile(counts, [1, input_size])
                    if input_size > 1 else counts)

        # For each input, pass counts to all elements selected by indices
        value_counts = [(process_input(v_input, v_value), v_value)
                        for v_input, v_value
                        in zip(self._values, value_values)]
        # TODO: Scatter to input tensors can be merged with tiling to reduce
        # the amount of operations.
        return self._scatter_to_input_tensors(*value_counts)

    def _compute_log_mpe_path(self, counts, *value_values, add_random=False, use_unweighted=False):
        return self._compute_mpe_path(counts, *value_values)
